-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 01, 2021 at 04:21 AM
-- Server version: 10.4.18-MariaDB
-- PHP Version: 8.0.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bigdeal`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `imgUrl` varchar(255) NOT NULL,
  `link` varchar(255) NOT NULL,
  `intro` varchar(255) NOT NULL,
  `price` float NOT NULL,
  `sold` int(11) NOT NULL,
  `number-rating` float NOT NULL,
  `description` varchar(1500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `imgUrl`, `link`, `intro`, `price`, `sold`, `number-rating`, `description`) VALUES
(1, 'images/ImagesOfResultPage/1.png', 'productpage.php', 'Basics In-Ear Wired Headphones, Earbuds with Microphone,Black', 34.99, 11, 4.3, 'Excellent Sound Performance: In-ear headphones can reduce external noise and sound leakage to a large extent. Powerful bass-driven stereo makes you get pure sound and comfortable sound range experience. Gold-plated plugs are also very suitable for lossless sound quality transmission||Built-in Microphone and Volume Control: In-ear headphones with high-quality mic and volume control can provide you a high-definition call experience, convenient and sensitive operation, support for answering/hanging up calls, playing/pausing music, increase/decrease volume and previous/next track.||Comfortable Sense of Use: Three different sizes of soft eartips (S/M/L) use a kind of flexible silicone material and ergonomic in-ear design to achieve a personalized fit to your auricle, making you wear without any discomfort.||Compatible Devices: Wired earphones are widely compatible with Computer/Laptop/Mobile Phone/iPad/MP3/MP4/PS4 and other devices with 3.5mm headphones port.||Fashion Style and Portability: Lightweight and comfortable in-ear headphones with stylish and exquisite appearance are ideal for work, study, sports and games, allowing you to enjoy the convenience of earbuds anytime and anywhere.'),
(2, 'images/ImagesOfResultPage/2.png', '#', 'Sonitum On Ear Headphones with Microphone, Wired Head Phones with Volume', 19.99, 96, 3.7, 'BLAZE THE HOTTEST BEATS AS YOUR ROCK THESE HEADSETS IN STYLE - Want to listen to music on the way to school? Need a solid pair of quality earphones to relax on your train or bus ride while dropping the hottest tracks around? Then you need to check out the M45 headphones that provide an all-encompassing almost immersive surrounding experience of crisp, clear audio sound!||AVOID THE HECTIC ATMOSPHERE AROUND WITH THIS NOISE ISOLATING HEADSET – With powerful internal precision noise reduction headphones and top wired circuitry, our headsets effectively eliminate up to 85% of background noise allowing you to listen undisturbed to songs, audiobooks or even talk on the phone. drift effortlessly into the magical land of music while traveling to school or aboard.||HIGH QUALITY HI-FI SOUND FOR AN UNPARALLED AUDITORY EXPERIENCE - Stereo wired set premium 40mm diameter driver units ensure a high-quality auditory experience encompassing a rich symmetry of bass as well as a powerful, balanced sound to listen to videos or music in enjoyment. Powerful 50-1600Hz frequency to adjust sound perfectly.'),
(3, 'images/ImagesOfResultPage/3.png', '#', 'Sony MDRZX110/BLK ZX Series Stereo Headphones (Black)', 69.99, 50, 4.6, 'Maximizing your personal audio experience has never been easier than with SONY ZX-Series Monitor headphones. Built with comfort and performance in mind, there\'s no need to compromise.||30mm drivers for rich, full frequency response||Lightweight and comfortable Over-ear design||Swivel-design for portability'),
(4, 'images/ImagesOfResultPage/4.png', '#', 'Mpow CH6S Kids Headphones with Microphone Over Ear, On Ear Headphones for Kids with HD Sound Sharing Function for Children Boys Girls', 39.99, 2, 4.4, 'Hi-fi stereo sound: stereo kids headphones with excellent sound effect, 3. 5mm plug compatible with all 3. 5mm jack devices. Distinct volume control switch & built in microphone: features distinct switch that can limits volume to 85Db with the press on, to protect hearing of your child and answer phone call while using with Phone. While in a noisy environment like car or Aero plane, the volume can be adjusted to a normal sound with the press off.||Happy sharing: the kids headphones provides easy access to 2 devices simultaneously connected, for a delightful sharing with friends and families. No more splitter is troubled||Comfortable fit: The plush circular cups fit perfectly on your ears and provide a comfortable listening experience you can use all day. Pinch-free hinges keep your little one’s fingers safe. The easy adjustable headband allows you to get the perfect fit. The headband is also made of plush leather material to so it’s comfortable to wear, so much so you might forget you are wearing headphones.||Support: Mow headphones life hassle-free- and quickly response customer service, for any questions while using, Please contact us at any time via email or through the Contact information on the instructions'),
(5, 'images/ImagesOfResultPage/5.png', '#', 'Sony MDRZX110/BLK ZX Series Stereo Headphones (Black)', 69.99, 50, 4.6, 'BLAZE THE HOTTEST BEATS AS YOUR ROCK THESE HEADSETS IN STYLE - Want to listen to music on the way to school? Need a solid pair of quality earphones to relax on your train or bus ride while dropping the hottest tracks around? Then you need to check out the M45 headphones that provide an all-encompassing almost immersive surrounding experience of crisp, clear audio sound!||AVOID THE HECTIC ATMOSPHERE AROUND WITH THIS NOISE ISOLATING HEADSET – With powerful internal precision noise reduction headphones and top wired circuitry, our headsets effectively eliminate up to 85% of background noise allowing you to listen undisturbed to songs, audiobooks or even talk on the phone. drift effortlessly into the magical land of music while traveling to school or aboard.||HIGH QUALITY HI-FI SOUND FOR AN UNPARALLED AUDITORY EXPERIENCE - Stereo wired set premium 40mm diameter driver units ensure a high-quality auditory experience encompassing a rich symmetry of bass as well as a powerful, balanced sound to listen to videos or music in enjoyment. Powerful 50-1600Hz frequency to adjust sound perfectly.'),
(6, 'images/ImagesOfResultPage/6.png', '#', 'Bluetooth Over-Ear Headphones, Zihnic Foldable Wireless and Wired Stereo Headset Micro SD/TF, FM for Cell Phone,PC,Soft Earmuffs', 23.99, 225, 3.9, 'ASTONISHING SOUND PRODUCTION : High Definition Stereo Headphones, specially developed software and noise reduction technology designed to prevent you from heating ambient noises and makes you focus on what you want to hear. Lose yourself in immersive music even in the lowest volume levels! The goal that provide Customers with outstanding sound quality is our constant pursuit||BUILT FOR YOUR COMFORTABILITY: The Earmuff imitate human skin texture, ensuring lasting comfort. They are foldable and stretchable, which allows you to find the perfect fit without constraint and excellent durability. Zihnic is the best Choice for Travel, Sport and Every day use by Unisex Kids, Teens and Adults.||SEAMLESS BLUETOOTH CONNECTION: Built to provide a quick and stable Bluetooth connection . Just slide the on/off button and the headphones will be in ready to pair mode. The Wireless Headphones are compatible with all Bluetooth or 3.5mm plug cable enabled devices! You can also receive calls and have hands-free communication through the special noise reduction technology microphone Zihnic Headphones are compatible with all Phones X, 8 Plus, Samsung S9, S8, Pads, Pods, Huawei, Nexus, Amazon Alexa'),
(7, 'images/ImagesOfResultPage/7.png', '#', 'Headphones with Microphone, Vogek Lightweight Foldable on Ear Headset for Kids Teens Adults, Wired Stereo Headphones with Deep Bass', 32.99, 165, 3.6, 'Hi-fi stereo sound: stereo kids headphones with excellent sound effect, 3. 5mm plug compatible with all 3. 5mm jack devices. Distinct volume control switch & built in microphone: features distinct switch that can limits volume to 85Db with the press on, to protect hearing of your child and answer phone call while using with Phone. While in a noisy environment like car or Aero plane, the volume can be adjusted to a normal sound with the press off.||Happy sharing: the kids headphones provides easy access to 2 devices simultaneously connected, for a delightful sharing with friends and families. No more splitter is troubled||Comfortable fit: The plush circular cups fit perfectly on your ears and provide a comfortable listening experience you can use all day. Pinch-free hinges keep your little one’s fingers safe. The easy adjustable headband allows you to get the perfect fit. The headband is also made of plush leather material to so it’s comfortable to wear, so much so you might forget you are wearing headphones.||Support: Mow headphones life hassle-free- and quickly response customer service, for any questions while using, Please contact us at any time via email or through the Contact information on the instructions'),
(8, 'images/ImagesOfResultPage/8.png', '#', 'Anker Soundcore Life Q20 Hybrid Active Noise Cancelling Headphones, Wireless Over Ear Bluetooth Headphones, 40H Playtime, Hi-Res Audio, Deep Bass', 45.99, 326, 4.8, 'ASTONISHING SOUND PRODUCTION : High Definition Stereo Headphones, specially developed software and noise reduction technology designed to prevent you from heating ambient noises and makes you focus on what you want to hear. Lose yourself in immersive music even in the lowest volume levels! The goal that provide Customers with outstanding sound quality is our constant pursuit||BUILT FOR YOUR COMFORTABILITY: The Earmuff imitate human skin texture, ensuring lasting comfort. They are foldable and stretchable, which allows you to find the perfect fit without constraint and excellent durability. Zihnic is the best Choice for Travel, Sport and Every day use by Unisex Kids, Teens and Adults.||SEAMLESS BLUETOOTH CONNECTION: Built to provide a quick and stable Bluetooth connection . Just slide the on/off button and the headphones will be in ready to pair mode. The Wireless Headphones are compatible with all Bluetooth or 3.5mm plug cable enabled devices! You can also receive calls and have hands-free communication through the special noise reduction technology microphone Zihnic Headphones are compatible with all Phones X, 8 Plus, Samsung S9, S8, Pads, Pods, Huawei, Nexus, Amazon Alexa'),
(9, 'images/ImagesOfResultPage/9.png', '#', 'Genuine Samsung Handsfree Headphones Earphones & Mic EO-EG900 for S10 S9 S8', 55.99, 43, 3.8, 'BLAZE THE HOTTEST BEATS AS YOUR ROCK THESE HEADSETS IN STYLE - Want to listen to music on the way to school? Need a solid pair of quality earphones to relax on your train or bus ride while dropping the hottest tracks around? Then you need to check out the M45 headphones that provide an all-encompassing almost immersive surrounding experience of crisp, clear audio sound!||AVOID THE HECTIC ATMOSPHERE AROUND WITH THIS NOISE ISOLATING HEADSET – With powerful internal precision noise reduction headphones and top wired circuitry, our headsets effectively eliminate up to 85% of background noise allowing you to listen undisturbed to songs, audiobooks or even talk on the phone. drift effortlessly into the magical land of music while traveling to school or aboard.||HIGH QUALITY HI-FI SOUND FOR AN UNPARALLED AUDITORY EXPERIENCE - Stereo wired set premium 40mm diameter driver units ensure a high-quality auditory experience encompassing a rich symmetry of bass as well as a powerful, balanced sound to listen to videos or music in enjoyment. Powerful 50-1600Hz frequency to adjust sound perfectly.'),
(10, 'images/ImagesOfResultPage/10.png', '#', 'Genuine Samsung Galaxy J3 J5 A3 A5 A7 S7 Edge Headset Earphones EO-EG920BW', 78.99, 24, 4.2, 'Hi-fi stereo sound: stereo kids headphones with excellent sound effect, 3. 5mm plug compatible with all 3. 5mm jack devices. Distinct volume control switch & built in microphone: features distinct switch that can limits volume to 85Db with the press on, to protect hearing of your child and answer phone call while using with Phone. While in a noisy environment like car or Aero plane, the volume can be adjusted to a normal sound with the press off.||Happy sharing: the kids headphones provides easy access to 2 devices simultaneously connected, for a delightful sharing with friends and families. No more splitter is troubled||Comfortable fit: The plush circular cups fit perfectly on your ears and provide a comfortable listening experience you can use all day. Pinch-free hinges keep your little one’s fingers safe. The easy adjustable headband allows you to get the perfect fit. The headband is also made of plush leather material to so it’s comfortable to wear, so much so you might forget you are wearing headphones.||Support: Mow headphones life hassle-free- and quickly response customer service, for any questions while using, Please contact us at any time via email or through the Contact information on the instructions'),
(11, 'images/ImagesOfResultPage/11.png', '#', 'bluetooth 5.0 Headset TWS Wireless Earphones Mini Earbuds Stereo Bass Headphones', 129.99, 11, 4, 'Maximizing your personal audio experience has never been easier than with SONY ZX-Series Monitor headphones. Built with comfort and performance in mind, there\'s no need to compromise.||30mm drivers for rich, full frequency response||Lightweight and comfortable Over-ear design||Swivel-design for portability'),
(12, 'images/ImagesOfResultPage/12.png', '#', 'New bluetooth earphone handsfree headset mini wireless earbuds for IOS & Xiaomi', 118.99, 23, 4.2, 'BLAZE THE HOTTEST BEATS AS YOUR ROCK THESE HEADSETS IN STYLE - Want to listen to music on the way to school? Need a solid pair of quality earphones to relax on your train or bus ride while dropping the hottest tracks around? Then you need to check out the M45 headphones that provide an all-encompassing almost immersive surrounding experience of crisp, clear audio sound!||AVOID THE HECTIC ATMOSPHERE AROUND WITH THIS NOISE ISOLATING HEADSET – With powerful internal precision noise reduction headphones and top wired circuitry, our headsets effectively eliminate up to 85% of background noise allowing you to listen undisturbed to songs, audiobooks or even talk on the phone. drift effortlessly into the magical land of music while traveling to school or aboard.||HIGH QUALITY HI-FI SOUND FOR AN UNPARALLED AUDITORY EXPERIENCE - Stereo wired set premium 40mm diameter driver units ensure a high-quality auditory experience encompassing a rich symmetry of bass as well as a powerful, balanced sound to listen to videos or music in enjoyment. Powerful 50-1600Hz frequency to adjust sound perfectly.'),
(13, 'images/ImagesOfResultPage/13.png', '#', 'Bluetooth 5.0 Earphones Wireless Earbuds IPX4 Waterproof Sports Headphones D2Y6', 44.99, 42, 4.4, 'Maximizing your personal audio experience has never been easier than with SONY ZX-Series Monitor headphones. Built with comfort and performance in mind, there\'s no need to compromise.||30mm drivers for rich, full frequency response||Lightweight and comfortable Over-ear design||Swivel-design for portability'),
(14, 'images/ImagesOfResultPage/14.png', '#', 'NEW 2021 Xiaomi Redmi AirDots 2 Wireless Bluetooth 5.0 Earphone In-Ear', 38.99, 28, 3.9, 'BLAZE THE HOTTEST BEATS AS YOUR ROCK THESE HEADSETS IN STYLE - Want to listen to music on the way to school? Need a solid pair of quality earphones to relax on your train or bus ride while dropping the hottest tracks around? Then you need to check out the M45 headphones that provide an all-encompassing almost immersive surrounding experience of crisp, clear audio sound!||AVOID THE HECTIC ATMOSPHERE AROUND WITH THIS NOISE ISOLATING HEADSET – With powerful internal precision noise reduction headphones and top wired circuitry, our headsets effectively eliminate up to 85% of background noise allowing you to listen undisturbed to songs, audiobooks or even talk on the phone. drift effortlessly into the magical land of music while traveling to school or aboard.||HIGH QUALITY HI-FI SOUND FOR AN UNPARALLED AUDITORY EXPERIENCE - Stereo wired set premium 40mm diameter driver units ensure a high-quality auditory experience encompassing a rich symmetry of bass as well as a powerful, balanced sound to listen to videos or music in enjoyment. Powerful 50-1600Hz frequency to adjust sound perfectly.'),
(15, 'images/ImagesOfResultPage/15.png', '#', 'Redmi Airdots 2 TWS Bluetooth Wireless Earphone Stereo Bass Earbuds', 17.99, 348, 3.6, 'Maximizing your personal audio experience has never been easier than with SONY ZX-Series Monitor headphones. Built with comfort and performance in mind, there\'s no need to compromise.||30mm drivers for rich, full frequency response||Lightweight and comfortable Over-ear design||Swivel-design for portability'),
(58, 'images/imagesOfResultPage/thumb16.jpg', '', 'Earphone ', 19.99, 99, 3.7, 'Para1||Para2||Description');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=59;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
